version: '2.1'
services:
  db:
    build:
      context: ./Docker
      dockerfile: Dockerfile.db
    image: zerg/db
    environment:
      sa_password: "29hHzGtB"
      ACCEPT_EULA: "Y"
    networks:
      default:
        aliases:
          - zergdb
  web:
    build:
      context: ../..
      dockerfile: samples/ZergRushCo.Todosya/Docker/Dockerfile.web
    image: zerg/web
    depends_on:
      - "db"
    ports:
      - "8080:80"
    volumes:
      - "temp:C:/Temp2"
    networks:
      default:
        aliases:
          - zergweb

networks:
  default:
    external:
      name: nat

volumes:
  temp:
